"""initial schema

Revision ID: 2d9834b3b591
Revises: 
Create Date: 2026-04-15 17:08:10.559732
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2d9834b3b591'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True, comment='ISO 639-1 code; NULL = all languages'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facebook_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('profile_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'MONITORED', 'FLAGGED', 'REPORTED', 'CLEARED', name='profilestatus'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('total_posts_analyzed', sa.Integer(), nullable=False),
    sa.Column('flagged_posts_count', sa.Integer(), nullable=False),
    sa.Column('reported_posts_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_facebook_id'), 'profiles', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_profiles_status'), 'profiles', ['status'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facebook_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.Enum('PAGE', 'GROUP', 'PROFILE', 'HASHTAG', name='targettype'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=False, comment='How often to scan this target'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1=low 2=medium 3=high'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_facebook_id'), 'targets', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_targets_target_type'), 'targets', ['target_type'], unique=False)
    op.create_table('keyword_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword_set_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False, comment='1=low 2=medium 3=high'),
    sa.Column('added_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Why this term is in the list'),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_set_id'], ['keyword_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_entries_keyword_set_id'), 'keyword_entries', ['keyword_set_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facebook_id', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('parent_post_facebook_id', sa.String(length=128), nullable=True, comment='For comments: the parent post ID'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('post_type', sa.Enum('POST', 'COMMENT', 'SHARE', 'STORY', name='posttype'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RAW', 'ANALYZED', 'FLAGGED', 'REPORTED', 'CLEARED', name='poststatus'), nullable=False),
    sa.Column('screenshot_s3_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_facebook_id'), 'posts', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_posts_posted_at'), 'posts', ['posted_at'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_target_id'), 'posts', ['target_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('hate_speech_score', sa.Float(), nullable=False),
    sa.Column('hate_speech_label', sa.String(length=64), nullable=True, comment='Model-specific output label'),
    sa.Column('was_translated', sa.Boolean(), nullable=False),
    sa.Column('claim_check_score', sa.Float(), nullable=False),
    sa.Column('claim_check_verdict', sa.String(length=128), nullable=True),
    sa.Column('matched_keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('keyword_severity', sa.Integer(), nullable=False),
    sa.Column('overall_label', sa.Enum('HATE_SPEECH', 'DISINFORMATION', 'KEYWORD_MATCH', 'CLEAN', name='analysislabel'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_overall_label'), 'analysis_results', ['overall_label'], unique=False)
    op.create_index(op.f('ix_analysis_results_overall_score'), 'analysis_results', ['overall_score'], unique=False)
    op.create_index(op.f('ix_analysis_results_post_id'), 'analysis_results', ['post_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SUBMITTING', 'SUBMITTED', 'FAILED', 'SKIPPED', name='reportstatus'), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'ACTIONED', 'REJECTED', 'UNKNOWN', name='reportoutcome'), nullable=False),
    sa.Column('report_category', sa.String(length=128), nullable=False, comment='hate_speech | false_information | harassment'),
    sa.Column('evidence_s3_key', sa.String(length=512), nullable=True),
    sa.Column('meta_reference_id', sa.String(length=256), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=64), nullable=False, comment='system or operator username'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_post_id'), 'reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_post_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_analysis_results_post_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_overall_score'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_overall_label'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_posts_target_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_posted_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_index(op.f('ix_posts_facebook_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_keyword_entries_keyword_set_id'), table_name='keyword_entries')
    op.drop_table('keyword_entries')
    op.drop_index(op.f('ix_targets_target_type'), table_name='targets')
    op.drop_index(op.f('ix_targets_facebook_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_profiles_status'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_facebook_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('keyword_sets')
    # ### end Alembic commands ###
